contentColumnType: string
fieldGroup: bf3fb46e-26a9-40ec-bf82-56b09b94d31d
handle: pageBuilder
instructions: ''
name: 'Page Builder'
searchable: false
settings:
  contentTable: '{{%matrixcontent_pagebuilder}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
