dateModified: 1597434349
email:
  fromEmail: codingwithkyle@gmail.com
  fromName: 'Papertrain Templator'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  eager-beaver:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  imager:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  smith:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Papertrain Templator'
  schemaVersion: 3.5.12
  timeZone: America/Los_Angeles
