field: 55aba7e0-fd38-4d2d-98fe-c1dd51e8302a
fieldLayouts:
  7e64b811-4616-4835-ad8a-8a1f09a856d0:
    tabs:
      -
        elements:
          -
            fieldUid: 6dfc07a7-6291-416f-b80e-4dc8b374969b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4855380c-d6d1-4a10-8f3f-64a777938938
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4855380c-d6d1-4a10-8f3f-64a777938938:
    contentColumnType: string
    fieldGroup: null
    handle: matrixField
    instructions: ''
    name: 'Matrix Field'
    searchable: true
    settings:
      contentTable: '{{%matrixcontent_matrixfield}}'
      maxBlocks: ''
      minBlocks: ''
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
  6dfc07a7-6291-416f-b80e-4dc8b374969b:
    contentColumnType: text
    fieldGroup: null
    handle: superTableHeading
    instructions: ''
    name: 'Super Table Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
